language: android
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+

script:
    - ./gradlew clean test
    - ./gradlew clean assemble

deploy:
    - provider: script
      script: scripts/deploy.sh
      on:
        # switch to master
        all_branches: true
