language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+

before_script:
    - yes | sdkmanager "platforms;android-28"

script:
    - ./gradlew clean build

deploy:
    - provider: script
      script: scripts/deploy.sh
      on:
        tags: true
