language: android
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+

script:
    - ./gradlew clean test
    - ./gradlew clean assemble
